### ISSUE TITLE
Add a semicolon (;) at the end of statements

### ISSUE THREAD

**Issue by simoneduca** [trangcongthanh/vscode-react-redux-snippets#1]
Currently, ESLint throws errors for missing semicolons, as [it should](https://davidwalsh.name/javascript-semicolons). So it'd be nice to have them in the snippets, instead of having to add them manually.

**Comment by trangcongthanh** [comment]
In my team, we don't use semicolon in our code. But I'll add semicolon in next version.

Example: 
`mdtp;`
It'll be:
`const mapDispatchToProps = dispatch => bindActionCreators({ actions }, dispatch);`

Is it good? If you have any idea for support semicolon, just let's me know.

**Comment by trangcongthanh** [comment]
Released v0.3.0 support semicolon

**Comment by simoneduca** [comment]
That's brilliant, thank you!
